@echo off
color 04
echo LOL YOU IDIOT LOL YOU GOT HACKED XDXDXD YOU DOWNLOADED VIRUS HAHAHAHHA
echo Call msgbox("XDXDX YOU HAVE BEEN HACKED BY VIRUS XD LOL LMFAO" ,4096, "LOLOLOLOLOLOL YOU ARE AN IDIOT") > virus.vbs
virus.vbs
color 02
echo SAY GOODBYE TO YOUR MONEY
echo Call msgbox("Accuiring credit card info..." ,4096, "Hacked lol") > virus.vbs
virus.vbs
color 01
echo YOULL NEVER SEE YOUR ROBUX AGAIN
echo Call msgbox("Accuiring passwords..." ,4096, "ill steal your vbucks") > virus.vbs
virus.vbs
echo FBI OPEN UP
echo Call msgbox("Accuiring IP..." ,4096, "Now i got your location lol") > virus.vbs
virus.vbs
echo FBI OPEN UP!!!
echo Call msgbox("IP is 420.6.9.0" ,4096, "XD") > virus.vbs
virus.vbs
echo REEEEEEEEEEEEEEEE
echo Call msgbox("Calling FBI..." ,4096, "youshouldnthavewatchedthatloliporn") > virus.vbs
virus.vbs
pause